FROM node:22.12.0

WORKDIR /usr/src/app

COPY package.json ./
COPY package-lock.json ./

RUN npm install && npm install -g @angular/cli

COPY . .

EXPOSE 4200

CMD ["ng", "serve", "--host", "0.0.0.0"]