version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: mydatabase

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_container
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    volumes:
      - ./backend:/usr/src/app
    command: >
      sh -c "npm install && npm run start:dev"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_container
    ports:
      - "4200:4200"
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/src/app
    command: >
      sh -c "npm install && ng serve --host=0.0.0.0 --disable-host-check"