FROM node:22.12.0

WORKDIR /usr/src/app

COPY package.json ./
COPY package-lock.json ./

RUN npm install

RUN apt-get update && apt-get install -y tzdata

ENV TZ=Asia/Bangkok

RUN dpkg-reconfigure -f noninteractive tzdata

COPY . .

EXPOSE 3000

# Start the application
CMD ["npm", "run", "start:dev"]